# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('lobby_id', models.AutoField(primary_key=True, serialize=False)),
                ('lobby_name', models.TextField()),
                ('lobby_password', models.TextField()),
            ],
        ),
    ]
