# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='lobby_modus',
            field=models.TextField(default='bks'),
            preserve_default=False,
        ),
    ]
