# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0008_auto_20171020_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gamer',
            new_name='Profile',
        ),
    ]
