# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0009_auto_20171020_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lobby_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamemaster.Lobby'),
        ),
    ]
