# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilanzkreisspiel', '0001_initial'),
        ('gamemaster', '0014_auto_20171026_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='capital',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='powerplantfleet',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='bilanzkreisspiel.PowerPlantFleet'),
        ),
    ]
