# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0016_auto_20171026_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='powerplantfleet',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='bilanzkreisspiel.PowerPlantFleet'),
        ),
    ]
