# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0017_auto_20171026_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bks_status',
            field=models.BooleanField(default=False),
        ),
    ]
