# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilanzkreisspiel', '0004_timeblock_timeblock_number'),
        ('gamemaster', '0018_profile_bks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bks_timeblock',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='bilanzkreisspiel.Timeblock'),
        ),
    ]
