# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0021_profile_bks_timeblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bks_timeblock',
        ),
    ]
