# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilanzkreisspiel', '0004_timeblock_timeblock_number'),
        ('gamemaster', '0022_remove_profile_bks_timeblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bks_timeblock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bilanzkreisspiel.Timeblock'),
        ),
    ]
