# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0023_profile_bks_timeblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bks_timeblock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilanzkreisspiel.Timeblock'),
        ),
    ]
