# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0024_auto_20171107_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bks_timeblock',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='bilanzkreisspiel.Timeblock'),
        ),
    ]
