# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boersenspiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kraftwerke',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('maxLeistung', models.IntegerField(default=0)),
                ('verfuegbarkeit', models.FloatField(default=0)),
                ('volllaststunden', models.IntegerField(default=0)),
                ('idBrennstoff', models.IntegerField(default=0)),
                ('wirkungsgrad', models.FloatField(default=0)),
                ('fixkosten', models.FloatField(default=0)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Kraftwerke',
                'verbose_name_plural': 'Kraftwerke',
            },
        ),
        migrations.CreateModel(
            name='spielerkraftwerke',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idSpiel', models.IntegerField(default=0)),
                ('idSpieler', models.IntegerField(default=0, null=True)),
                ('idKraftwerk', models.IntegerField(default=0)),
                ('verkaufteEnergiemenge', models.IntegerField(default=0)),
                ('gewinn', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='spieler',
            name='deckungsbeitrag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spieler',
            name='idSpiel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='spieler',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
