# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boersenspiel', '0002_auto_20170907_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spieler',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
