# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boersenspiel', '0003_auto_20170907_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='gebote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSpiel', models.IntegerField(default=0, null=True)),
                ('idSpieler', models.IntegerField(default=0, null=True)),
                ('idRunde', models.IntegerField(default=0, null=True)),
                ('idKW', models.IntegerField(default=0, null=True)),
                ('idGebot', models.IntegerField(default=0, null=True)),
                ('Time', models.TimeField()),
                ('Menge', models.IntegerField(default=0, null=True)),
                ('Preis', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='spieler',
            name='Runde',
            field=models.IntegerField(default=1),
        ),
    ]
