# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boersenspiel', '0004_auto_20170908_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gebote',
            old_name='idRunde',
            new_name='Runde',
        ),
    ]
