# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boersenspiel', '0005_auto_20170908_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='spieler',
            name='idSpieler',
            field=models.IntegerField(default=False),
        ),
    ]
