# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boersenspiel', '0006_spieler_idspieler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spieler',
            name='id',
        ),
        migrations.AlterField(
            model_name='spieler',
            name='idSpieler',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
