# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 08:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boersenspiel', '0007_auto_20170922_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gebote',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='spieler',
            name='idSpieler',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
