# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 11:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boersenspiel', '0008_auto_20170922_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='boersenpreise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runde', models.IntegerField(default=0)),
                ('time', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('menge', models.IntegerField(default=0)),
                ('preis', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Boersenpreis',
                'verbose_name_plural': 'Boersenpreise',
            },
        ),
        migrations.CreateModel(
            name='ergebnisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSpiel', models.IntegerField(default=0)),
                ('idSpieler', models.IntegerField(default=0)),
                ('idRunde', models.IntegerField(default=0)),
                ('erloes', models.IntegerField(default=0)),
                ('kostenCo2', models.FloatField(default=0)),
                ('kosten', models.FloatField(default=0)),
                ('time', models.TimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Ergebnis',
                'verbose_name_plural': 'Ergebnisse',
            },
        ),
        migrations.CreateModel(
            name='lastgang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRunde', models.IntegerField(default=0)),
                ('fMaxLast', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Lastgang',
                'verbose_name_plural': 'Lastgaenge',
            },
        ),
        migrations.AlterModelOptions(
            name='gebote',
            options={'verbose_name': 'Gebot', 'verbose_name_plural': 'Gebote'},
        ),
        migrations.AlterModelOptions(
            name='spieler',
            options={'verbose_name': 'Spieler', 'verbose_name_plural': 'Spieler'},
        ),
        migrations.AlterModelOptions(
            name='spielerkraftwerke',
            options={'verbose_name': 'SpielderKraftwerk', 'verbose_name_plural': 'SpielerKraftwerke'},
        ),
    ]
