# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boersenspiel', '0009_auto_20170922_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='brennstoff',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('EMF', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Brennstoff',
                'verbose_name_plural': 'Brennstoffe',
            },
        ),
        migrations.CreateModel(
            name='brennstoffpreise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBrennstoff', models.IntegerField(default=0)),
                ('Runde', models.IntegerField(default=0)),
                ('Preis', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Brennstoffpreis',
                'verbose_name_plural': 'Brennstoffpeise',
            },
        ),
    ]
