# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boersenspiel', '0011_co2preise'),
    ]

    operations = [
        migrations.AddField(
            model_name='co2preise',
            name='Preis',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='co2preise',
            name='Runde',
            field=models.IntegerField(default=0),
        ),
    ]
