# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 05:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boersenspiel', '0012_auto_20170925_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='einstellungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Runde', models.IntegerField(default=0)),
                ('idSpiel', models.IntegerField(default=1)),
                ('auctiontype', models.IntegerField(default=1)),
                ('nextround', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('rundenzeit', models.IntegerField(default=180)),
            ],
        ),
        migrations.AlterModelOptions(
            name='co2preise',
            options={'verbose_name': 'CO2 Preis', 'verbose_name_plural': 'CO2 Preise'},
        ),
    ]
