# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boersenspiel', '0013_auto_20170926_0744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='einstellungen',
            options={'verbose_name': 'Einstellungen', 'verbose_name_plural': 'Einstellungen'},
        ),
    ]
