# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 08:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boersenspiel', '0014_auto_20170926_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einstellungen',
            name='nextround',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
