# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boersenspiel', '0015_auto_20170926_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spieler',
            name='Runde',
        ),
    ]
