# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('day_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_number', models.IntegerField()),
                ('day_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.TextField()),
                ('event_discription', models.TextField()),
                ('event_duration', models.IntegerField()),
                ('event_feed_in', models.IntegerField()),
                ('event_feed_out', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PowerPlantFleet',
            fields=[
                ('powerplantfleet_id', models.AutoField(primary_key=True, serialize=False)),
                ('powerplantfleet_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PowerStation',
            fields=[
                ('powerstation_id', models.AutoField(primary_key=True, serialize=False)),
                ('powerstation_name', models.TextField()),
                ('powerstation_current_feed_in', models.IntegerField()),
                ('powerstation_current_feet_out', models.IntegerField()),
                ('powerstation_powerplantfleet', models.ManyToManyField(to='bilanzkreisspiel.PowerPlantFleet')),
            ],
        ),
        migrations.CreateModel(
            name='Timeblock',
            fields=[
                ('timeblock_id', models.AutoField(primary_key=True, serialize=False)),
                ('timeblock_duration', models.IntegerField()),
                ('timeblock_day', models.ManyToManyField(to='bilanzkreisspiel.Day')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_from_timeblock',
            field=models.ManyToManyField(to='bilanzkreisspiel.Timeblock'),
        ),
    ]
