# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilanzkreisspiel', '0002_auto_20171027_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeblock',
            name='timeblock_day',
        ),
        migrations.AddField(
            model_name='timeblock',
            name='timeblock_day',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='bilanzkreisspiel.Day'),
        ),
    ]
