# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilanzkreisspiel', '0003_auto_20171027_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='timeblock_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
